server {
    listen 80;
    server_name nl82.torcalc.ru;
    root /var/www/nl82.torcalc.ru;
    index index.html;
    server_tokens off;
    charset utf-8;
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/acme;
        default_type text/plain;
        try_files $uri =404;
    }
    location / { try_files $uri $uri/ =404; }
    location ~ /\. { deny all; }
}
